<?xml version="1.0" encoding="utf-8"?><Database Name="ELDB" Class="dcShareDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=wnl;Initial Catalog=ELDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ELDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Division" Member="Divisions">
    <Type Name="Division">
      <Column Name="Division_code" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Division_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Division_status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Emp" Member="Emps">
    <Type Name="Emp">
      <Column Name="Emp_code" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Division_code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Emp_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Emp_status" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Emp_salary" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.chat" Member="chats">
    <Type Name="chat">
      <Column Name="chat_date" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="chat_from" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="chat_to" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="chat_msg" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="chat_state" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="chat_update" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>